version: '3'
services:
  jupyter:
    image: {{DOCKER_IMAGE}}
    container_name: {{DOCKER_IMAGE}}-jupyter
    volumes:
      - ./:/workspace/{{{PKG}}}.jl
    working_dir: /workspace/{{{PKG}}}.jl
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /workspace/{{{PKG}}}.jl --ip=0.0.0.0 --allow-root
  lab:
    image: {{DOCKER_IMAGE}}
    container_name: {{DOCKER_IMAGE}}-lab
    volumes:
      - ./:/workspace/{{{PKG}}}.jl
    working_dir: /workspace/{{{PKG}}}.jl
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /workspace/{{{PKG}}}.jl --ip=0.0.0.0 --allow-root
  julia:
    image: {{DOCKER_IMAGE}}
    container_name: {{DOCKER_IMAGE}}-julia
    volumes:
      - ./:/workspace/{{{PKG}}}.jl
    working_dir: /workspace/{{{PKG}}}.jl
    command: julia --project=/workspace/{{{PKG}}}.jl
  web:
    image: {{DOCKER_IMAGE}}
    container_name: {{DOCKER_IMAGE}}-packagedocs
    volumes:
      - ./:/workspace/{{{PKG}}}.jl
    working_dir: /workspace/{{{PKG}}}.jl
    ports:
      - "8000:8000"
    command: make web
  pluto:
    image: {{DOCKER_IMAGE}}
    container_name: {{DOCKER_IMAGE}}-pluto
    volumes:
      - ./:/workspace/{{{PKG}}}.jl
    working_dir: /workspace/{{{PKG}}}.jl
    ports:
      - "1234:1234"
    command: julia -e 'import Pluto; Pluto.run(host="0.0.0.0", port=1234)'
